### ISSUE TITLE
Dependency on ReachabilitySwift 4.3.1

### ISSUE THREAD

**Issue by pokryfka** [RxSwiftCommunity/RxReachability#20]
RxReachability works fine with ReachabilitySwift 4.3.0

On the other hand, 4.3.1 introduces dependency on Swift5,

see comment in https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/master/Podfile

**Comment by FouadAstitou** [comment]
@brennobemoura When will this be implemented? Because I am using 1.0.0 and it still depends on ReachabilitySwift 4.3.1

**Comment by brennobemoura** [comment]
The latest commit no develop is using ReachabilitySwift at version 5.0. As soon as possible, it will be a release to RxReachability

**Comment by JoeMatt** [comment]
Updated in 1.2.0
