### ISSUE TITLE
cocoa pods update?

### ISSUE THREAD

**Issue by FouadAstitou** [RxSwiftCommunity/RxReachability#26]
Can you please release 1.1.0 to cocoa pods? Currently cocoa pods still depends on ReachabilitySwift 4.3.1
Thanks in advance

**Comment by JoeMatt** [comment]
Hi, 

I just got assigned ownership of the project on GitHub. I have to get admin access through CocoaPods though to make any schema changes.

Will work on that, might take a minute unless someone knows a quick way to accesss an admin at cocoapods spec repo.

**Comment by JoeMatt** [comment]
#37 is a blocker for this isue

**Comment by Antonito** [comment]
Hi,

I'm also looking forward to this update, it's a blocker for a SDK I'm writing.

Thanks! 😊

**Comment by JoeMatt** [comment]
> Hi,
> 
> I'm also looking forward to this update, it's a blocker for a SDK I'm writing.
> 
> Thanks! 😊

You should be able to override the default podspec and point to 'master'. 

It's a stable release branch with an updated podsec. The issue I have is I don't have admin access yet to Cocoapods central repo update system. Actually need to contact them about that still if I knew whom to contact that will actually respond.

**Comment by Antonito** [comment]
> > Hi,
> > I'm also looking forward to this update, it's a blocker for a SDK I'm writing.
> > Thanks! 😊
> 
> You should be able to override the default podspec and point to 'master'.
> 
> It's a stable release branch with an updated podsec pointing to RxSwift 5.0.
> 
> The issue I have is I don't have admin access yet to Cocoapods central repo update system. Actually need to contact them about that still if I knew whom to contact that will actually respond.

Thank you for the very quick reply!

I wish I could, but as far as I know, it's not possible in my situation. My SDK has dependencies from both Carthage (whenever possible) & Cocoapods (for a very few number of libraries that don't work well with Carthage).
I'm using `RxReachability@master` & `ReachabilitySwift@5.0.0`, with Carthage.

My issue is I want to generate documentation with [Jazzy](https://github.com/realm/jazzy), which doesn't integrate well with Carthage.
My solution to that is to write a `${PROJECT_NAME}-Documentation.podspec` file, that lists dependencies from both Carthage & Cocoapods.
And unfortunately it seems it's not possible to specify a git source for a `s.dependency`, hence dependency resolution failure...

**Comment by JoeMatt** [comment]
I just got publishing rights from CocoaPods team. 

It's on my agenda for the next rainy day to push the spec upstream. Winter is coming.

**Comment by JoeMatt** [comment]
Published to ccpods.
