### ISSUE TITLE
Conform to git-flow standards

### ISSUE THREAD

**Issue by JoeMatt** [RxSwiftCommunity/RxReachability#37]
## Overview

Currently, everything is merged to `master`. This is considered bad form imho.

I intend to use a standard `git-flow` branch naming scheme

## Requirements

1. Create a `develop` branch
2. Change the default branch to `develop` (required to Pull Requests automatically are set to said branch as the base)
3. Lock pushes to `master` for everyone
4. Lock pushes to `develop` for everyone, require PR checks to pass for merge, allow admins to force push over-ride

2-4 requires I get admin control of this repo, waiting on @freak4pc or whomever else is a current admin to upgrade my ownership rights on this project.

**Comment by freak4pc** [comment]
Hey Joseph, We usually don’t give admin writes to individual repo owners but only membership. 
I’ve added you as a Maintainer which is a level below Admin but should still grant you most options. If you’re missing any specific capabilities, let me me know.
