### ISSUE TITLE
Dependency won't build on Xcode 12.4 using SPM

### ISSUE THREAD

**Issue by ferusinfo** [RxSwiftCommunity/RxReachability#42]
## Describe the bug

While moving all of our dependencies from CocoaPods to SPM, the only library that won't build at the moment is RxReachability, therefore blocking us from moving all of our Rx related dependencies to the SPM.

Problem lies in the underlying dependency to Reachability.swift which does not specify the minimum version. Xcode 12 is now treating iOS8 Target as a warning, so all of SPM modules without clearly defined minimal version is resolving to iOS 9.0.

At the same time, RxReachability have a requirement still pointing to iOS 8 as a minimal version, creating an error while building:

`The package product 'Reachability' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0`

## To Reproduce

Try to use RxReachability via SPM on Xcode >= 12.4

## Expected behavior

I want to use RxReachability via SPM on newest Xcode.

**Comment by EvanCooper9** [comment]
I think #43 should fix this

**Comment by JoeMatt** [comment]
#43 fixes
