### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by sebanitu** [RxSwiftCommunity/RxReachability#45]
## Overview

SPM Support

## Reasons

RxReachability is one of the very few Rx dependencies that do not support SPM.

**Comment by JoeMatt** [comment]
Should work if you point to develop until a new release tag is pushed out.

https://github.com/RxSwiftCommunity/RxReachability/blob/develop/Package.swift

**Comment by JoeMatt** [comment]
closed by #46
