### ISSUE TITLE
Can you please change the small syntax error while installing pod it should be  -> pod 'RxReachability', '~> 1.2.1' you misplaced symbol. Thank you!

### ISSUE THREAD

**Issue by JasurSalimov** [RxSwiftCommunity/RxReachability#48]
## Describe the bug

Can you please change the small syntax error while installing pod it should be  -> pod 'RxReachability', '~> 1.2.1' you misplaced symbol. Thank you!

**Comment by JoeMatt** [comment]
Misplaced which symbol in which file?

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/399864/147392607-5eb46648-ce32-45f2-8390-392e2c0fd6f9.png">

**Comment by JasurSalimov** [comment]
In installation guide on the main framework github page.
